// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"github.com/reation/home_order_service/internal/logic"
	"github.com/reation/home_order_service/internal/svc"
	"github.com/reation/home_order_service/proto/types/proto"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetOrderInfoByID(ctx context.Context, in *proto.Id) (*proto.OrderInfo, error) {
	l := logic.NewGetOrderInfoByIDLogic(ctx, s.svcCtx)
	return l.GetOrderInfoByID(in)
}

func (s *UserServer) GetOrderInfoByOid(ctx context.Context, in *proto.OrderId) (*proto.OrderInfo, error) {
	l := logic.NewGetOrderInfoByOidLogic(ctx, s.svcCtx)
	return l.GetOrderInfoByOid(in)
}

func (s *UserServer) GetOrderInfoByUid(ctx context.Context, in *proto.UserId) (*proto.OrderInfo, error) {
	l := logic.NewGetOrderInfoByUidLogic(ctx, s.svcCtx)
	return l.GetOrderInfoByUid(in)
}

func (s *UserServer) GetOrderListByUid(ctx context.Context, in *proto.UserId) (*proto.OrderListResponse, error) {
	l := logic.NewGetOrderListByUidLogic(ctx, s.svcCtx)
	return l.GetOrderListByUid(in)
}
