// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package user

import (
	"context"

	"github.com/reation/home_order_service/proto/types/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Id                = proto.Id
	OrderId           = proto.OrderId
	OrderInfo         = proto.OrderInfo
	OrderListResponse = proto.OrderListResponse
	UserId            = proto.UserId

	User interface {
		GetOrderInfoByID(ctx context.Context, in *Id, opts ...grpc.CallOption) (*OrderInfo, error)
		GetOrderInfoByOid(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*OrderInfo, error)
		GetOrderInfoByUid(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*OrderInfo, error)
		GetOrderListByUid(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*OrderListResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetOrderInfoByID(ctx context.Context, in *Id, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetOrderInfoByID(ctx, in, opts...)
}

func (m *defaultUser) GetOrderInfoByOid(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetOrderInfoByOid(ctx, in, opts...)
}

func (m *defaultUser) GetOrderInfoByUid(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetOrderInfoByUid(ctx, in, opts...)
}

func (m *defaultUser) GetOrderListByUid(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*OrderListResponse, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetOrderListByUid(ctx, in, opts...)
}
